Add scripts folder in hex package
kafka4beam/brod pull request #353
Opened 2019-11-01 10:06 UTC by srijan

Enables using as a dependency with erlang.mk via hex.pm

2019-11-01 12:21 UTC, k32 commented
Hi! Thanks for your PR. Do you use brod with Erlang.mk? I am wondering because actually we considered removing support for this build system in the future.

2019-11-01 13:44 UTC, srijan commented
> Hi! Thanks for your PR. Do you use brod with Erlang.mk? I am wondering because actually we considered removing support for this build system in the future.

We use erlang.mk, and have started using brod recently.

I think you can safely remove support for building with erlang.mk and shift to rebar3 without affecting our use case.

Erlang.mk supports using rebar3 compatible libraries as dependencies.

2019-11-06 15:35 UTC, k32 commented
Do you need some particular script to build brod with Erlang.mk? I realized that some of the scripts in the "scripts" directory should not be exposed to the outer world: they are for CI, testing and what not.

2019-11-07 04:49 UTC, srijan commented
@k32, the Makefile target for `compile` has `vsn-check` as dependency:

```
vsn-check:
	@./scripts/vsn-check.sh $(PROJECT_VERSION)
```

I didn't go too deep into what it does. If it's not needed, another way to resolve this would be to remove this dependency.

2019-11-07 07:03 UTC, k32 commented
Thanks for the answer. I think vsn_check dependency can be simply removed. Recently I made some  changes that make rebar3 use git tag as a source of truth. So significance of this script has diminished.

2019-11-07 08:01 UTC, srijan commented
It looks like the `vsn-check.sh` script just compares versions of dependencies defined in Makefile and in rebar.config, and exits with an error if there is a mismatch.

If you're only using rebar for building, then I think this script can be removed completely.

2019-11-07 08:38 UTC, k32 commented
Agree.

2019-11-07 10:37 UTC, srijan commented
Should I amend this PR to completely remove erlang.mk (while still keeping it compatible to be used as a dependency in an erlang.mk project) ?

Or should I just make changes required to make it work for now as an erlang.mk project dependency by removing vsn check script?

2019-11-07 10:41 UTC, k32 commented
I think it's better to start by removing version check dependency in the makefile first. Removing support for Erlang.mk alltogether is a breaking change that deserves a major version bump.

2019-11-07 13:49 UTC, k32 requested changes

2019-11-07 13:49 UTC, k32 commented on src/brod.app.src
> +  {files, ["src", "include", "scripts", "rebar.config", "rebar.config.script",
Internal scripts should not be packaged

2019-11-08 06:14 UTC, srijan commented
There's still an issue.

The default target in the Makefile is `app`, which uses erlang.mk to build.
In the current state:

1. If a repo using erlang.mk includes brod as a dependency using git -> it builds using erlang.mk (using dependency details specified in Makefile)
2. If a repo using erlang.mk includes brod as a dependency using hex -> build fails because `vsn-check.sh` does not exist in hex package
3. If a repo using rebar3 includes brod as a dependency -> it builds using rebar3 (using dependency details specified in rebar.config)

The `vsn-check.sh` script ensures that the dependency versions (for supervisor3 and kafka_protocol) defined in rebar.config and Makefile do not go out of sync.

_So, as long as the dependency version is defined both in the Makefile and rebar.config, `vsn-check.sh` should not be removed._

My scenario is case 2.

**Solution 1:** include the `vsn-check.sh` file in the hex package. (Not recommended)

**Solution 2:** Only define dependencies in rebar.config. Erlang.mk supports reading dependency information from rebar.config. But, for this, erlang.mk would have to be completely removed from this repo. If erlang.mk file is present, it assumes dependencies are defined in Makefile.

**Solution 3:** (recommended)
Remove vsn-check from the Makefile dependency of `app` and `compile` targets, while still keeping it in the `t` target (used for testing, called in travis.yml).
This way, all 3 cases above will work, and travis will still complain if Makefile and rebar.config dependencies ever go out of sync.

I recommend solution 3 for the short term, and solution 2 can be planned for the next major version bump.

@k32, please confirm, and I'll update the diff accordingly.

2019-11-08 07:11 UTC, k32 commented
Hi!
You are correct. Option 3 is the best short-term solution.

2019-11-08 08:07 UTC, zmstone commented
vsn-check is already a dependency for target `t`
Suggestion: change 
`app:: vsn-check`
To
`app::`
Otherwise 
`app:: dummy`

2019-11-08 09:33 UTC, k32 approved these changes

2019-11-08 13:04 UTC, k32 commented
Hi! Looks good to me. Please update the changelog.

2019-11-11 07:40 UTC, k32 approved these changes

2019-11-11 07:41 UTC, k32 commented
Thanks for the PR!

2019-11-11 07:42 UTC, merged

2019-11-13 15:26 UTC, k32 commented
@srijan Brod 3.9.3 that includes your patch has been released